# ---------------------------------
# DiscordChatMC Configuration v1.0
# ---------------------------------

# The token for your bot from the Discord Developers site.
bot-token: ""
# The ID of your server.
guild: 0
# The Discord invite URL that will be shown when a player when using the /discord command or in other areas.
discord-url: ""

# Channels defined here can be used in the section below to specify which channel a message goes to.
# If a defined channel ID is invalid, the primary channel will be used as a fallback.
# If the primary channel is not defined or invalid, the default channel of the server will be used.
# If your server doesn't have any text channels, the plugin will be disabled.
# By default, two channels are defined:
# - primary, which will send basic join/leave/death/chat messages
# - staff, which will send kick/mute messages
# (note: you will need to replace the zeros with the actual channel ID you want to use)
channels:
  primary: 0
  staff: 0

chat:
  # Discord normal max length
  discord-max-length: 2000
  # Add a prefix before the name, only on the discord message (e.g [PRX] varen)
  name-prefix: ""

# Configure which Discord channels different messages will be sent to.
# You can either use the names of the channels listed above or just the id of a channel.
# If an invalid channel is used, the primary channel will be used instead.
#
# To disable a message from showing, use 'none' as the channel name.
message-types:
  # Join messages sent when a player joins the Minecraft server.
  join: primary
  # Join messages sent when a player joins the Minecraft server for the first time. This type is sent instead of the join type.
  first-join: primary
  # Leave messages sent when a player leaves the Minecraft server.
  leave: primary
  # Chat messages sent when a player chats on the Minecraft server.
  chat: primary
  # Death messages sent when a player dies on the Minecraft server.
  death: primary
  # AFK status change messages sent when a player's AFK status changes.
  afk: primary
  # Achievement/advancement messages sent when a player is awarded an achievement/advancement.
  advancement: primary
  # Action messages sent when a player runs the /me or /action commands.
  action: primary
  # Message sent when the server starts up.
  server-start: primary
  # Message sent when the server shuts down.
  server-stop: primary
  # Message sent when a player is kicked from the Minecraft server.
  kick: staff
  # Message sent when a player's mute state is changed on the Minecraft server.
  mute: staff
  # Message sent when a private message (/msg, /whisper, etc.) is sent on the Minecraft Server.
  private-chat: none
  # Message sent when a player talks in local chat.
  local: none
  # Message sent when a player asks a question in global chat.
  question: primary
  # Message sent when a player talks in global chat.
  shout: primary

# Whether or not fake join and leave messages should be sent to Discord when a player toggles vanish in Minecraft.
# Fake join/leave messages will be sent the same as real join and leave messages (and to the same channel).
vanish-fake-join-leave: true
# Whether or not messages from vanished players should be sent to Discord.
# This affects join, leave, death, and afk message types by default.
vanish-hide-messages: true

# Whether or not player messages should show their avatar as the profile picture in Discord.
# The bot will require the "Manage Webhooks" permission in the defined channels in order to use this feature.
show-avatar: false
# The URL which should be used to get the avatars of users when "show-avatar" is set to true.
# Any URL in here should only return a proper JPEG/PNG image and nothing else.
# For offline-mode, you can add SkinsRestorer + PlaceholderAPI, and use this link instead "https://mc-heads.net/avatar/%skinsrestorer_texture_id_or_steve%"
# For online-mode, you can use this link "https://crafatar.com/avatars/{uuid}"
# Just copy and paste it into avatar-url
avatar-url: "https://mc-heads.net/avatar/"

# Settings pertaining to the varies commands registered.
commands:
  # The execute command allows for Discord users to execute MC commands from Discord.
  # MC commands executed by this will be ran as the console and you should therefore be careful to who you grant this to.
  execute:
    # Set to false if you do not want this command to show up on the Discord command selector.
    # You must restart your server after changing this.
    enabled: true
    # Whether or not the command should be hidden from other people in the channel.
    # If set to false, members of the Discord guild will be able to see the exact command you executed as well as its response.
    hide-command: true
    # List of user IDs or role names/IDs allowed to use this command (or * to allow anyone to access it).
    allowed-roles:
      - "Admins"
      - "123456789012345678"
  # The msg command allows for Discord users to message MC players from Discord.
  msg:
    # Set to false if you do not want this command to show up on the Discord command selector.
    # You must restart your server after changing this.
    enabled: true
    # Whether or not the command should be hidden from other people in the channel.
    # If set to false, members of the Discord guild will be able to see the target and content of your message.
    hide-command: true
    # List of user IDs or role names/IDs allowed to use this command (or '*' to allow anyone to access it).
    allowed-roles:
      - "*"
    # List of user IDs or role names/IDs who can message vanished players or players who disable messages. If '*' is
    # used, all people on Discord would be allowed to message vanished players (and therefore expose they are actually online)
    # and message players who disable messages.
    admin-roles:
      - "Admins"
      - "123456789012345678"
  # The list command allows Discord users to see a list of players currently online on Minecraft.
  list:
    # Set to false if you do not want this command to show up on the Discord command selector.
    # You must restart your server after changing this.
    enabled: false
    # Whether or not the command should be hidden from other people in the channel.
    # If set to false, members of the Discord guild will be able to see when you use this command as well as its response.
    hide-command: true
    # List of user IDs or role names/IDs allowed to use this command (or '*' to allow anyone to access it).
    allowed-roles:
      - "*"
    # List of user IDs or role names/IDs who can see vanished players in the player list. If '*' is used, all people
    # on Discord would be allowed to see vanished players (and therefore expose they are actually online).
    admin-roles:
      - "Admins"
      - "123456789012345678"

# The presence of the bot, including its status, activity and status message.
presence:
  # The online status of the bot. Must be one of the following:
  # - "online": Shows as green circle (Online)
  # - "idle": Shows as yellow half-circle (Away)
  # - "dnd": Shows as red circle (Do Not Disturb)
  # - "invisible": Makes the bot appear offline
  status: online
  # The activity of the bot to be prefixed before your message below. Must be one of the following;
  # - "playing": Shows up as "Playing <message>"
  # - "listening": Shows up as "Listening to <message>"
  # - "watching": Shows up as "Watching <message>"
  # - "competing": Shows up as "Competing in <message>"
  # - "none": Don't show any activity message
  activity: "playing"
  # The activity status message.
  message: "Minecraft"

messages:
  # This is the message that is used to show Discord chat to players in game.
  # Color/formatting codes and the following placeholders can be used here:
  # - {channel}: The name of the Discord channel the message was sent from
  # - {username}: The username of the user who sent the message
  # - {discriminator}: The four numbers displayed after the user's name
  # - {fullname}: Equivalent to typing "{username}#{discriminator}"
  # - {nickname}: The nickname of the user who sent the message. (Will return username if user has no nickname)
  # - {role}: The name of the user's topmost role on Discord. If the user doesn't have a role, the placeholder is empty.
  # - {color}: The minecraft color representative of the user's topmost role color on Discord. If the user doesn't have a role color, the placeholder is empty.
  # - {message}: The content of the message being sent
  discord-to-mc: "&6[#{channel}] &3{fullname}&7: &f{message}"
  # This is the message that is used to relay minecraft chat in Discord.
  # The following placeholders can be used here:
  # - {username}: The username of the player sending the message
  # - {displayname}: The display name of the player sending the message (This would be their nickname)
  # - {message}: The content of the message being sent
  # - {world}: The name of the world the player sending the message is in
  # - {prefix}: The prefix of the player sending the message
  # - {suffix}: The suffix of the player sending the message
  # ... PlaceholderAPI placeholders are also supported here too!
  mc-to-discord: "{displayname}: {message}"
  # This is the bot's name which appears in Discord when sending player-specific messages.
  # The following placeholders can be used here:
  # - {username}: The username of the player sending the message
  # - {displayname}: The display name of the player sending the message (This would be their nickname)
  # - {world}: The name of the world the player sending the message is in
  # - {prefix}: The prefix of the player sending the message
  # - {suffix}: The suffix of the player sending the message
  # - {botname}: Name of the Discord bot
  # ... PlaceholderAPI placeholders are also supported here too!
  mc-to-discord-name-format: "{displayname}"
  # This is the message that is used to relay minecraft local chat in Discord.
  # The following placeholders can be used here:
  # - {username}: The username of the player sending the message
  # - {displayname}: The display name of the player sending the message (This would be their nickname)
  # - {message}: The content of the message being sent
  # - {world}: The name of the world the player sending the message is in
  # - {prefix}: The prefix of the player sending the message
  # - {suffix}: The suffix of the player sending the message
  # ... PlaceholderAPI placeholders are also supported here too!
  mc-to-discord-local: "**[Local]** {displayname}: {message}"
  # This is the message that is used to relay questions from minecraft chat in Discord.
  # The following placeholders can be used here:
  # - {username}: The username of the player sending the message
  # - {displayname}: The display name of the player sending the message (This would be their nickname)
  # - {message}: The content of the message being sent
  # - {world}: The name of the world the player sending the message is in
  # - {prefix}: The prefix of the player sending the message
  # - {suffix}: The suffix of the player sending the message
  # ... PlaceholderAPI placeholders are also supported here too!
  mc-to-discord-question: "**[Question]** {displayname}: {message}"
  # This is the message that is used to relay minecraft global chat in Discord.
  # The following placeholders can be used here:
  # - {username}: The username of the player sending the message
  # - {displayname}: The display name of the player sending the message (This would be their nickname)
  # - {message}: The content of the message being sent
  # - {world}: The name of the world the player sending the message is in
  # - {prefix}: The prefix of the player sending the message
  # - {suffix}: The suffix of the player sending the message
  # ... PlaceholderAPI placeholders are also supported here too!
  mc-to-discord-shout: "**[Shout]** {displayname}: {message}"
  # This is the message sent to Discord when a player is temporarily muted in minecraft.
  # The following placeholders can be used here:
  # - {username}: The username of the player being muted
  # - {displayname}: The display name of the player being muted
  # - {controllername}: The username of the user who muted the player
  # - {controllerdisplayname}: The display name of the user who muted the player
  # - {time}: The amount of time the player was muted for
  temporary-mute: "{controllerdisplayname} has muted player {displayname} for {time}."
  # This is the message sent to Discord when a player is temporarily muted (with a reason specified) in minecraft.
  # The following placeholders can be used here:
  # - {username}: The username of the player being muted
  # - {displayname}: The display name of the player being muted
  # - {controllername}: The username of the user who muted the player
  # - {controllerdisplayname}: The display name of the user who muted the player
  # - {time}: The amount of time the player was muted for
  # - {reason}: The reason the player was muted for
  temporary-mute-reason: "{controllerdisplayname} has muted player {displayname} for {time}. Reason: {reason}."
  # This is the message sent to Discord when a player is permanently muted in minecraft.
  # The following placeholders can be used here:
  # - {username}: The username of the player being muted
  # - {displayname}: The display name of the player being muted
  # - {controllername}: The username of the user who muted the player
  # - {controllerdisplayname}: The display name of the user who muted the player
  permanent-mute: "{controllerdisplayname} has muted player {displayname}."
  # This is the message sent to Discord when a player is permanently muted (with a reason specified) in minecraft.
  # The following placeholders can be used here:
  # - {username}: The username of the player being muted
  # - {displayname}: The display name of the player being muted
  # - {controllername}: The username of the user who muted the player
  # - {controllerdisplayname}: The display name of the user who muted the player
  # - {reason}: The reason the player was muted for
  permanent-mute-reason: "{controllerdisplayname} has permanently muted player {displayname}. Reason: {reason}."
  # This is the message sent to Discord when a player is unmuted in minecraft.
  # The following placeholders can be used here:
  # - {username}: The username of the player being unmuted
  # - {displayname}: The display name of the player being unmuted
  unmute: "{displayname} unmuted."
  # This is the message sent to Discord when a player joins the minecraft server.
  # The following placeholders can be used here:
  # - {username}: The name of the user joining
  # - {displayname}: The display name of the user joining
  # - {joinmessage}: The full default join message used in game
  # - {online}: The amount of players online
  # - {unique}: The amount of unique players to ever join the server
  # ... PlaceholderAPI placeholders are also supported here too!
  join: ":arrow_right: {displayname} has joined!"
  # This is the message sent to Discord when a player joins the minecraft server for the first time.
  # The following placeholders can be used here:
  # - {username}: The name of the user joining
  # - {displayname}: The display name of the user joining
  # - {joinmessage}: The full default join message used in game
  # - {online}: The amount of players online
  # - {unique}: The amount of unique players to ever join the server
  # ... PlaceholderAPI placeholders are also supported here too!
  first-join: ":arrow_right: :first_place: {displayname} has joined the server for the first time!"
  # This is the message sent to Discord when a player leaves the minecraft server.
  # The following placeholders can be used here:
  # - {username}: The name of the user leaving
  # - {displayname}: The display name of the user leaving
  # - {quitmessage}: The full default leave message used in game
  # - {online}: The amount of players online
  # - {unique}: The amount of unique players to ever join the server
  # ... PlaceholderAPI placeholders are also supported here too!
  quit: ":arrow_left: {displayname} has left!"
  # This is the message sent to Discord when a player dies.
  # The following placeholders can be used here:
  # - {username}: The name of the user who died
  # - {displayname}: The display name of the user who died
  # - {deathmessage}: The full default death message used in game
  # ... PlaceholderAPI placeholders are also supported here too!
  death: ":skull: {deathmessage}"
  # This is the message sent to Discord when a player becomes afk.
  # The following placeholders can be used here:
  # - {username}: The name of the user who became afk
  # - {displayname}: The display name of the user who became afk
  # ... PlaceholderAPI placeholders are also supported here too!
  afk: ":person_walking: {displayname} is now AFK!"
  # This is the message sent to Discord when a player is no longer afk.
  # The following placeholders can be used here:
  # - {username}: The name of the user who is no longer afk
  # - {displayname}: The display name of the user who is no longer afk
  # ... PlaceholderAPI placeholders are also supported here too!
  un-afk: ":keyboard: {displayname} is no longer AFK!"
  # This is the message sent to Discord when a player is awarded an advancement.
  # The following placeholders can be used here:
  # - {username}: The name of the user who was awarded the advancement.
  # - {displayname}: The display name of the user who was awarded the advancement.
  # - {advancement}: The name of the advancement.
  # ... PlaceholderAPI placeholders are also supported here too!
  advancement: ":medal: {displayname} has completed the advancement **{advancement}**!"
  # This is the message sent to Discord when a player runs the /me or /action command.
  # The following placeholders can be used here:
  # - {username}: The name of the user who ran the command
  # - {displayname}: The display name of the user who ran the command
  # - {action}: The action (message) the user used in the command.
  # ... PlaceholderAPI placeholders are also supported here too!
  action: ":person_biking: {displayname} *{action}*"
  # This is the message sent to Discord when the server starts.
  # - {starttimeseconds}: The amount of seconds it took to start the server (measured from JVM start time).
  server-start: ":white_check_mark: The server has started in {starttimeseconds} seconds!"
  # This is the message sent to Discord when the server stops.
  server-stop: ":octagonal_sign: The server has stopped!"
  # This is the message sent to Discord when a player is kicked from the server.
  # The following placeholders can be used here:
  # - {username}: The name of the user who got kicked
  # - {displayname}: The display name of the user who got kicked
  # - {reason}: The reason the player was kicked
  kick: "{displayname} was kicked with reason: {reason}"
  # This is the message that is used to relay minecraft private messages in Discord.
  # The following placeholders can be used here:
  # - {sender-username}: The username of the player sending the message
  # - {sender-displayname}: The display name of the player sending the message (This would be their nickname)
  # - {receiver-username}: The username of the player receiving the message
  # - {receiver-displayname}: The display name of the player receiving the message (This would be their nickname)
  # - {message}: The content of the message being sent
  pms-to-discord: "[SocialSpy] {sender-username} -> {receiver-username}: {message}"
